spring:
  application:
    name: gpt-bot

web:
  max-idle-time: 1
  max-life-time: 10

telegram:
  url: ${TELEGRAM_URL}
  bot-token: ${TELEGRAM_BOT_TOKEN}
  bot-secret: ${TELEGRAM_BOT_SECRET}
  timeout: 30
  retry-attempts: 2
  retry-backoff: 100

auth:
  users: ${REGISTERED_USERS}

openai:
  api-key: ${OPENAI_API_KEY}
  organization-id: ${OPENAI_ORG_ID}
  project-id: ${OPENAI_PROJECT_ID}